### ISSUE TITLE
Build web is not supported on beta channel version image

### ISSUE THREAD

**Issue by balazsbokanyi** [cirruslabs/docker-images-flutter#118]
Hello,

for the past few weeks, I've been using the cirrusci/flutter:beta image in my CI/CD environment to build flutter for the web. However, for some reason, I can't use the currently latest beta channel release (1.25.0-8.1.pre), I want to stick to the previous one, 1.24.0-10.2.pre.

After modifying my pipeline to use the cirrusci/flutter:1.24.0-10.2.pre image, the _flutter build web_ command exits with **"build web is not currently supported"**.

I assumed that an image with the beta channel version supports building for the web. Is my assumption wrong? If I want to build web I have to use the flutter:beta image, or is this could be a bug?

flutter build web output:

flutter build web -t lib/web/web_main.dart
   Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
  /
📎
Downloading Web SDK...                                           2,159ms
Running "flutter pub get" in build...                              706ms
"build web" is not currently supported.

**Comment by fkorotkov** [comment]
I think you need to run `flutter config --enable-web` regardless of the image tag you are using. 🤔

**Comment by balazsbokanyi** [comment]
Thanks for the response!

With the _beta_ image, I do not have to run _flutter config_, flutter build web works fine without it.

On the other hand, after running _flutter config --enable-web_ in image 1.24.0-10.2.pre, _flutter build web_ also works as expected.
