### ISSUE TITLE
Cannot open file, path = './pubspec.lock' (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by tl-yang** [cirruslabs/docker-images-flutter#12]
My Dockerfile: 
```
FROM cirrusci/flutter

WORKDIR /app
COPY pubspec.yaml /app/pubspec.yaml
COPY lib /app/lib
COPY test /app/test

RUN flutter doctor -v
RUN flutter test
```
where my project is just a startup project created like [this](https://flutter.dev/docs/get-started/test-drive?tab=terminal)
```flutter create myapp```

However, using [adamantium/flutter](https://hub.docker.com/r/adamantium/flutter) docker image worked well without problem?

**Comment by fkorotkov** [comment]
This image has a separate `cirrus` user and Docker doesn't respect it when coping a file (defaults permission on copied files to `root`). You'll need to fix it by adding the following after you've copied everything:

```Dockerfile
RUN sudo chown -R cirrus:cirrus /app
```

**Comment by danidavid** [comment]
chown command helped me by doing this in flutter. I don't know it's a good procedure to do, your feedbacks and suggestions are more welcomed. 

The command used is,

sudo chown -R $USER:root /path/to/main/directory
