### ISSUE TITLE
Using Emulators/devices

### ISSUE THREAD

**Issue by HrGaertner** [cirruslabs/docker-images-flutter#124]
Hello maybe this is a dumb question but could i  use a emulator or my device from the docker container? Thanks a lot

**Comment by fkorotkov** [comment]
Hey @HrGaertner, which OS you have?

**Comment by HrGaertner** [comment]
Linux (fedora)

**Comment by fkorotkov** [comment]
So we are talking about Android emulator/device. You can try to run the image with `--net=host` flag and then you should be able to connect to the devices.

**Comment by HrGaertner** [comment]
Ok, thanks a lot
