### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by vjcrypto** [cirruslabs/docker-images-flutter#13]
Getting this error while trying to run "flutter doctor" inside docker container

/home/cirrus/sdks/flutter/bin/flutter: line 177: /home/cirrus/sdks/flutter/bin/cache/dart-sdk/bin/dart: Permission denied

**Comment by fkorotkov** [comment]
@vjcrypto How exactly do you run it?

**Comment by vjcrypto** [comment]
I try to run your docker image from within a Jenkins environment

**Comment by fkorotkov** [comment]
Sorry I missed a notification and didn't follow up. 😿 Have you figured the issue? BTW just updated the images so it might be worth trying again.

**Comment by albru123** [comment]
I'm getting similar errors when trying to use the image in Azure Pipeline. The problem probably is that flutter is installed under the `cirrus` user, while runners like Jenkins and Azure Pipelines (which I'm trying to use) are using their own users inside the container. That results in access denied errors.

**Comment by fkorotkov** [comment]
Interesting. Don't they respect `USER` from the image metadata?

**Comment by albru123** [comment]
They don't, unfortunately. It really makes things unnecessary complicated. I guess they use their own user to make the build environment safer, as by default it is run under root.

**Comment by albru123** [comment]
You can see in the container initialization log that they create their own user
[container_initialization.txt](https://github.com/cirruslabs/docker-images-flutter/files/3462424/container_initialization.txt)

And here's the build error I'm facing
[build.txt](https://github.com/cirruslabs/docker-images-flutter/files/3462423/build.txt)

**Comment by fkorotkov** [comment]
It might make sense if they run on VMs but not inside Docker containers. 🤷‍♂ 

Not sure what to do about it. Cirrus CI for example respect the USER config. Unfortunately, I don't have enough knowledge about Azure Pipelines and quick googling didn't help much.

**Comment by epomatti** [comment]
I guess I'm having a similar problem with GitHub Actions.

This is the error I'm getting at "Install Dependencies" step:

```
Run flutter pub get
  flutter pub get
  shell: sh -e {0}
Running "flutter pub get" in cbpq-flutter...                    
Creation failed, path = '/github/home/.pub-cache' (OS Error: Permission denied, errno = 13)
pub get failed (66)
##[error]Process completed with exit code 66.
```

This [material](https://help.github.com/en/articles/virtual-environments-for-github-actions#docker-container-filesystem) about the filesystem also mentions the `USER`instruction.

**Comment by epomatti** [comment]
Adding `sudo` solved it for me in GitHub Actions:

```shell
# absolute path is required
sudo /home/cirrus/sdks/flutter/bin/flutter pub get
```
Also from the Actions docs:

> The Linux and macOS virtual machines both run using passwordless sudo. When you need to execute commands or install tools that require more privileges than the current user, you can use sudo without needing to provide a password.

**Comment by shmink** [comment]
I also get the error when trying to get in my yml that get's ran on my repo using github actions.

```
Running "flutter pub get" in something-to-eat...                
Creation failed, path = '/github/home/.pub-cache' (OS Error: Permission denied, errno = 13)
pub get failed (66)
##[error]Process completed with exit code 66.
```

**Comment by evandropomatti** [comment]
@shmink check my last answer. You'll need to use `sudo` and consequently use the absolute path to your Flutter installation. Like this: 

```
sudo /home/cirrus/sdks/flutter/bin/flutter pub get
```

**Comment by fkorotkov** [comment]
Created #45 to make is easier to run in GitLab
