### ISSUE TITLE
cirrusci/flutter:2.2.0-10.2.pre is pointing to 2.3.0-0.1.pre

### ISSUE THREAD

**Issue by cmc5788** [cirruslabs/docker-images-flutter#152]
@fkorotkov when the latest `cirrusci/flutter:2.2.0-10.2.pre` image is pulled, it's actually been built with `2.3.0-0.1.pre` as the `flutter --version`. This is causing CI errors for us. Any ideas?

**Comment by fkorotkov** [comment]
Not sure what's going on there:

```
docker run cirrusci/flutter:2.2.0-10.2.pre flutter --version
Flutter 2.3.0-0.1.pre • channel 2.2.0-10.2.pre • https://github.com/flutter/flutter.git
Framework • revision d72bfb8d07 (8 days ago) • 2021-04-26 06:05:55 -0700
Engine • revision de6e1adf97
Tools • Dart 2.14.0 (build 2.14.0-18.0.dev)
```

It points to `channel 2.2.0-10.2.pre` but the version is 2.3.0-0.1.pre. 🤔

**Comment by fkorotkov** [comment]
They do both point to the same commit:

https://github.com/flutter/flutter/tree/2.2.0-10.2.pre
https://github.com/flutter/flutter/tree/2.3.0-0.1.pre

**Comment by cmc5788** [comment]
I guess the dev channel was updated to point to the same commit as beta, and the `flutter --version` command isn't quite so straightforward. Thanks for the info. I'll try to just adjust the version checking logic we use to pick the `channel 2.2.0-10.2.pre` part of the output to assert against instead of the first part...

**Comment by fkorotkov** [comment]
Created https://github.com/flutter/flutter/issues/81835

**Comment by cmc5788** [comment]
Looks like it's not so easy to fix, since when the tools are locked to a channel the output is as follows:

```
Flutter 2.2.0-10.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision b5017bf8de (6 days ago) • 2021-04-28 17:09:53 -0700
Engine • revision 91ed51e05c
Tools • Dart 2.13.0 (build 2.13.0-211.13.beta)
```

To create one script that accurately checks if you're on the right version in this case will be tricky 🤔

**Comment by cmc5788** [comment]
@fkorotkov since Flutter fixed the duplicate version, would re-pushing the beta image fix this?

**Comment by fkorotkov** [comment]
I've already re-ran task to re-push. 

```console
❯ docker pull cirrusci/flutter:2.2.0-10.2.pre
2.2.0-10.2.pre: Pulling from cirrusci/flutter
a70d879fa598: Already exists 
c4394a92d1f8: Already exists 
10e6159c56c0: Already exists 
88b60d097db6: Already exists 
da8267fe4abd: Already exists 
a2f95a68111f: Pull complete 
dfddd4e89625: Pull complete 
Digest: sha256:fe2916f4427b7076afd307f6a476f6d167c5df35c6b904151f12cadb018a6b33
Status: Downloaded newer image for cirrusci/flutter:2.2.0-10.2.pre
docker.io/cirrusci/flutter:2.2.0-10.2.pre

~ on ☁️ fedor@cirruslabs.org took 37s 
❯ docker run cirrusci/flutter:2.2.0-10.2.pre flutter --version
Flutter 2.2.0-10.2.pre • channel unknown • unknown source
Framework • revision b5017bf8de (6 days ago) • 2021-04-28 17:09:53 -0700
Engine • revision 91ed51e05c
Tools • Dart 2.13.0 (build 2.13.0-211.13.beta)
```

**Comment by cmc5788** [comment]
Re-ran our CI jobs and everything seems good now. Thanks for digging into this so quickly!
