### ISSUE TITLE
Support (headless) browser as a target for running test

### ISSUE THREAD

**Issue by truongsinh** [cirruslabs/docker-images-flutter#17]
example `pub run test test -p chrome`

**Comment by fkorotkov** [comment]
@truongsinh do you have an example repo where it can be tested?

**Comment by truongsinh** [comment]
@fkorotkov you can take a look at https://github.com/zino-app/graphql-flutter/pull/311

Please be noticed that it is a mono repo, thus after cloning:
```
cd  packages/graphql
pub run test test -p chrome
```
