### ISSUE TITLE
Image update

### ISSUE THREAD

**Issue by psrcek** [cirruslabs/docker-images-flutter#178]
Recently, the [DST ROOT CA X3](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/) expired. This caused our builds to start failing because we are using packages from git repositories that are hosted with Let's Encrypt certificates. All that is needed to fix this is a simple rebuild of the image (`apt update && apt upgrade` in the container also fixes this issue since it updates the `ca-certificates` package)

**Comment by fkorotkov** [comment]
Merging of #177 should pull the latest base image with fresher certificates from cirruslabs/docker-images-android#38. Please check and let me know if there are any issues.
