### ISSUE TITLE
Currently not on an official channel

### ISSUE THREAD

**Issue by ghezeli** [cirruslabs/docker-images-flutter#188]
Hi 
when I try to use this container
i get this error

![image](https://user-images.githubusercontent.com/5620958/146006047-0607ce08-a4eb-46ce-9a9c-f280ea551a09.png)

**Comment by gquarles** [comment]
Can confirm this is causing issues

https://cirrus-ci.com/task/5750437126078464

**Comment by fkorotkov** [comment]
I think it's because we [do a shallow clone](https://github.com/cirruslabs/docker-images-flutter/blob/4b35624565ca25133cb9faedd9ee8204c94b48c1/sdk/Dockerfile#L13) in order to make the image smaller. 

@gquarles I thinking running `flutter channel stable` doesn't make sense if you already use the `stable` tag. You can try to do the following though:

```yaml
unshallow_script: cd $FLUTTER_HOME && git fetch --unshallow
```

**Comment by gquarles** [comment]
@fkorotkov Thank you! 
You are right about switching to stable when already on the stable branch, I have been stumbling around trying to fix a package I use. 

When I try and run git fetch --unshallow inside of the docker image it doesn't find any other branches still and the flutter tool fails to switch to any other branches. Is there a different tag that would work for switching between channels or should I use multiple docker instances for the different channels?

**Comment by fkorotkov** [comment]
Actually maybe you need to `git fetch --unshallow --all --tags`. Could you please try that? 🤔

**Comment by gquarles** [comment]
That gives me `fatal: --unshallow on a complete repository does not make sense`

**Comment by ghezeli** [comment]
This problem has not been fixed for me yet
I make the container with this command
docker run --rm -it -v $ {PWD}: / build --workdir / build cirrusci / flutter: stable
And I still have a problem

![image](https://user-images.githubusercontent.com/5620958/149229212-111227bb-5f9f-468a-b44d-a5ff11ce45ad.png)

**Comment by fkorotkov** [comment]
@ghezeli I don't think anything can be done to fix these "issues". There is no need in Chrome or Android studio itself to build apps in a container.

**Comment by gquarles** [comment]
Yea I agree @fkorotkov, I proposed changes to remove testing on multiple channels in the repo I was working on as I feel testing on master really is not that needed as master changes every day. The only way I can see to allow this would be to increase the size of the image by a lot so I don't think it would be worth it IMO.
