### ISSUE TITLE
Add gradle home for flutter android

### ISSUE THREAD

**Issue by Hoang-Nguyenn** [cirruslabs/docker-images-flutter#199]
Hi. We're now working with fastlane and build android but seem need to manual download and export environment for gradle from this one 
https://gist.github.com/Ashok-Varma/6b5864c1e444a3f1b61158254a43c4bc
It would be great if you guys can help us to add gradle environment for flutter docker.

**Comment by Hoang-Nguyenn** [comment]
Maybe can only add this command to step run binsh 

wget https://services.gradle.org/distributions/gradle-6.7.1-bin.zip -P /tmp
sudo unzip -d /opt/gradle /tmp/gradle-*.zip
export GRADLE_HOME="/opt/gradle/gradle-6.7.1/bin"
export PATH=${PATH}:$GRADLE_HOME
gradle -v

![image](https://user-images.githubusercontent.com/81745635/159202836-88addaf5-61c4-4179-afbf-b30d8fc536ad.png)

**Comment by fkorotkov** [comment]
I believe the recommended way is to use a [Gradle Wrapper `./gradlew` script](https://docs.gradle.org/current/userguide/gradle_wrapper.html). Otherwise Gradle will be yet another dependency to upgrade within the image.

**Comment by Hoang-Nguyenn** [comment]
> I believe the recommended way is to use a [Gradle Wrapper `./gradlew` script](https://docs.gradle.org/current/userguide/gradle_wrapper.html). Otherwise Gradle will be yet another dependency to upgrade within the image.

I'm using fastlane for build android in ci machine now. I got problem that we ignore gradlew file in android folder. And i got ./gradlew not found. Do you have any suggestion ?

![image](https://user-images.githubusercontent.com/81745635/159651024-df112e0e-9347-4d32-ac0f-c5b146b43ea9.png)

**Comment by Hoang-Nguyenn** [comment]
> > I believe the recommended way is to use a [Gradle Wrapper `./gradlew` script](https://docs.gradle.org/current/userguide/gradle_wrapper.html). Otherwise Gradle will be yet another dependency to upgrade within the image.
> 
> I'm using fastlane for build android in ci machine now. I got problem that we ignore gradlew file in android folder. And i got ./gradlew not found. Do you have any suggestion ?
> 
> ![image](https://user-images.githubusercontent.com/81745635/159651024-df112e0e-9347-4d32-ac0f-c5b146b43ea9.png)

I'm using this script "./gradlew wrapper --gradle-version 6.7.1"

**Comment by fkorotkov** [comment]
I'd suggest to check in the `gradlew` script since it will allow you to pin Gradle version that you use for the app so the same version will be used among all the engineers and CI.
