### ISSUE TITLE
Building patched version of Flutter-CI

### ISSUE THREAD

**Issue by lloydrichards** [cirruslabs/docker-images-flutter#201]
greetings!  i'm working on an issue with the Flutter team to improve performance for testing in a CI environment.

https://github.com/flutter/flutter/issues/100751

We need to test a patched version of Flutter that they're working on but building a Docker Image for CI is a bit out of scope.  Would someone be able to help us out so we can benchmark and improve both Flutter and the Flutter-CI image 🙏 

To reduce cross-posting I think it would be better to just comment on the flutter issue and close this one if you would like to help :)

**Comment by fkorotkov** [comment]
You can try to modify [the git command](https://github.com/cirruslabs/docker-images-flutter/blob/9982f37ed1b44563800592cb2a92c897cb01f6cd/sdk/Dockerfile#L13) to checkout your changes. Then you can build the image locally and push it to some registry to consume from GitLab.

**Comment by lloydrichards** [comment]
This is where my knowledge of Docker starts to drop off.  So I've cloned the repo and added in my commands to where you specified.  But I don't know how to build this into a container for the registry.  i can run it locally with `docker run --rm -it -v ${PWD}:/build --workdir /build cirrusci/flutter:stable flutter test`  but `docker build .` just give me an error

**Comment by fkorotkov** [comment]
You can build your own tag via command like `docker build --tag my-docker-image-url:latest sdk`. Then you can push your image to your registry and reuse it.

Another option might be to use `cirrusci/android-sdk:30` image in your CI and duplicate [logic of configuring Flutter SDK](https://github.com/cirruslabs/docker-images-flutter/blob/9982f37ed1b44563800592cb2a92c897cb01f6cd/sdk/Dockerfile#L7-L17) as the first step of your CI.

**Comment by lloydrichards** [comment]
thanks so much.  i ended up doing something similar to the `cirrusci/android-sdk:30` image in  test CI for now while we debug with flutter :)
