### ISSUE TITLE
Crash when switching flutter channel

### ISSUE THREAD

**Issue by javihernant** [cirruslabs/docker-images-flutter#204]
`Switching to flutter channel 'stable'...

===== CRASH =====
si_signo=Segmentation fault(11), si_code=1, si_addr=0x808080808080809f
version=2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "linux_x64"
pid=57, thread=65, isolate_group=main(0x4002f9b000), isolate=main(0x4002f9d000)
isolate_instructions=4001e1b980, vm_instructions=4001e1b980
  pc 0x0000ffffb2d046a9 fp 0x000000400ff70408 Unknown symbol
  pc 0x0000ffffb2084589 fp 0x000000400ff70480 Unknown symbol
  pc 0x0000ffffb20842ec fp 0x000000400ff704e8 Unknown symbol
  pc 0x0000ffffb2083fa6 fp 0x000000400ff70580 Unknown symbol
  pc 0x0000ffffb17af669 fp 0x000000400ff70608 Unknown symbol
  pc 0x0000ffffb17af318 fp 0x000000400ff70660 Unknown symbol
  pc 0x0000ffffb17aef5d fp 0x000000400ff706a0 Unknown symbol
  pc 0x0000ffffb17aea48 fp 0x000000400ff706e0 Unknown symbol
  pc 0x0000ffffb17ae793 fp 0x000000400ff70720 Unknown symbol
  pc 0x0000ffffb17ae494 fp 0x000000400ff70760 Unknown symbol
  pc 0x0000ffffb20a19dd fp 0x000000400ff707a0 Unknown symbol
  pc 0x0000ffffb20fd1a5 fp 0x000000400ff70800 Unknown symbol
  pc 0x0000ffffb246e848 fp 0x000000400ff70850 Unknown symbol
  pc 0x0000ffffb2081743 fp 0x000000400ff70898 Unknown symbol
  pc 0x0000ffffb20813bb fp 0x000000400ff708d8 Unknown symbol
  pc 0x0000ffffb20812e9 fp 0x000000400ff70900 Unknown symbol
  pc 0x0000ffffb208120e fp 0x000000400ff70940 Unknown symbol
  pc 0x0000ffffb2a22bf8 fp 0x000000400ff70980 Unknown symbol
  pc 0x0000ffffb2d029bf fp 0x000000400ff709f8 Unknown symbol
  pc 0x0000004001f983fd fp 0x000000400ff70aa0 dart::DartEntry::InvokeCode(dart::Code const&, unsigned long, dart::Array const&, dart::Array const&, dart::Thread*)+0x14d
  pc 0x0000004001f9823c fp 0x000000400ff70b00 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x14c
  pc 0x0000004001f9a64f fp 0x000000400ff70b50 dart::DartLibraryCalls::HandleMessage(long, dart::Instance const&)+0x16f
  pc 0x0000004001fc14c5 fp 0x000000400ff70c30 dart::IsolateMessageHandler::HandleMessage(std::__2::unique_ptr<dart::Message, std::__2::default_delete<dart::Message> >)+0x375
  pc 0x0000004001fe958c fp 0x000000400ff70ca0 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x14c
  pc 0x0000004001fe9c8f fp 0x000000400ff70cf0 dart::MessageHandler::TaskCallback()+0x1df
  pc 0x0000004002103ab8 fp 0x000000400ff70d80 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x138
  pc 0x0000004002103f4c fp 0x000000400ff70db0 dart::ThreadPool::Worker::Main(unsigned long)+0x5c
  pc 0x000000400207ce28 fp 0x000000400ff70e70 /sdks/flutter/bin/cache/dart-sdk/bin/dart+0x207ce28
-- End of DumpStackTrace
qemu: uncaught target signal 6 (Aborted) - core dumped
/sdks/flutter/bin/internal/shared.sh: line 223:    57 Aborted                 "$DART" --disable-dart-dev --packages="$FLUTTER_TOOLS_DIR/.packages" $FLUTTER_TOOL_ARGS "$SNAPSHOT_PATH" "$@"
`

**Comment by javihernant** [comment]
Error shows up in m1 macs, works flawlessly in intel ones

**Comment by fkorotkov** [comment]
We don't have arm images at the moment unfortunately. Please follow #150 for progress.
