### ISSUE TITLE
Cannot start container, not sure how to debug

### ISSUE THREAD

**Issue by wyximb** [cirruslabs/docker-images-flutter#21]
any clue?

**Comment by fkorotkov** [comment]
@wyximb what are you trying to do? Which command are you trying to run?

**Comment by wyximb** [comment]
1. Cannot download flutter from Kitematic
2, Download it manually on Windows with "docker pull cirrusci/flutter"
3, docker create cirrusci/flutter
4, docker start a4e92cd7a1e5f755657d33017e9e9a62303570000c6afe189cc1fc69a14c4d7e
5, The container doesn't start.

**Comment by fkorotkov** [comment]
This container is not mean to be started. You can run some command like:

```bash
docker run -it cirrusci/flutter:stable /bin/bash
```

Or you can even mount your project and then you'll be able to build it inside the container.
