### ISSUE TITLE
Upgrade to Flutter 3.0.5

### ISSUE THREAD

**Issue by btrautmann** [cirruslabs/docker-images-flutter#220]
Hoping to get an image for 3.0.5 set up, release date was 7/13/22 per https://docs.flutter.dev/development/tools/sdk/releases?tab=macos.

Thank you!

**Comment by btrautmann** [comment]
Being addressed by https://github.com/cirruslabs/docker-images-flutter/pull/219

**Comment by mdeandrea-mrmilu** [comment]
This issue can be close
