### ISSUE TITLE
Gitlab CI Failures

### ISSUE THREAD

**Issue by izik1** [cirruslabs/docker-images-flutter#24]
```
Could not find a command named "sh".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
Could not find a command named "sh".

Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

I believe this to be caused by https://github.com/cirruslabs/docker-images-flutter/blob/7993d2f46bf3f1123de3fef93e053f394d39d0ba/sdk/Dockerfile#L16
Which sets the `ENTRYPOINT` to `flutter` , however, `CMD` is `sh`, which causes `flutter sh ...` to be ran, which is an error, as `flutter sh` is not a valid flutter command.

**Comment by fkorotkov** [comment]
@izik1 where do you see the error?

`docker run --rm -it -v ${PWD}:/build cirrusci/flutter:stable test` works for me.
