### ISSUE TITLE
Shell Not Found cirrusci/flutter:>3.1.0

### ISSUE THREAD

**Issue by rarawls** [cirruslabs/docker-images-flutter#250]
When changing my gitlab-ci image from `cirrusci/flutter:3.1.0` to any newer version, I get a `shell not found` error.  I have spent hours looking into it and cannot figure out what changed or how to get around it.

```console
Running with gitlab-runner 15.8.2 (4d1ca121)
  on <<<RUNNER INFO REDACTED>>>
  Preparing the "docker" executor
00:02
Using Docker executor with image cirrusci/flutter:[3](<<<REDACTED>>>).7.3 ...
Pulling docker image cirrusci/flutter:3.7.3 ...
Using docker image sha256:cc7832ad6c0e1bd1f46389e3425588fe0101b3be3e330c1faef66df1e92b501d for cirrusci/flutter:3.7.3 with digest cirrusci/flutter@sha256:f25f548211862a561bafeb7966bc9166b9e1106c1fe105cb95f0ffbd29dce47a ...
Preparing environment
00:01
Running on runner-87gi2mqy-project-328-concurrent-0 via 9aef8df41e4d...
Getting source from Git repository
00:02
Fetching changes with git depth set to 20...
Initialized empty Git repository in /builds/<<<PROJECT NAME>>>/.git/
Created fresh repository.
Checking out ae523a01 as build/test...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:01
Using docker image sha256:cc7832ad6c0e1bd1f[4](<<<DOCKER REGISTRY REDACTED>>> ...
shell not found
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by fkorotkov** [comment]
Have you seen https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27614? Seems it's a known issue with the latest Ubuntu based containers.

**Comment by rarawls** [comment]
Fun.  I had not seen that.  Thanks for the link

**Comment by rarawls** [comment]
Based on what I've looked after you directed me to the gitlab issue, it seems to me that what changed after cirrusci/flutter:3.1.0 is that you started using a newer version of Ubuntu for your image.  Is that the case?

**Comment by fkorotkov** [comment]
Seems so. The ubuntu switch was on June 17th, 2022: https://github.com/cirruslabs/docker-images-android/commit/cd2a41ec49be26c3e5482546385a55a32183f334. Seems like 3.1.0 was the last tag that used the previous image.

**Comment by rarawls** [comment]
Whelp.  Guess that's it then.  Thanks for your time and help.  Looks like this is in fact unrelated to cirrusci and can be closed.
