### ISSUE TITLE
Docker hub releases

### ISSUE THREAD

**Issue by jeanmatthieud** [cirruslabs/docker-images-flutter#264]
Hi,

Could you please push Flutter 3.7.8 and 3.7.9 to [Docker hub](https://hub.docker.com/r/cirrusci/flutter/tags)?

Thanks !

**Comment by fkorotkov** [comment]
We switched to GitHub Container Registry in #260 because of unclear messages from Docker Hub. Please switch to the GitHub Container Registry urls.

**Comment by jeanmatthieud** [comment]
Thanks!
You should edit the description on the Docker Hub to add a link to the new registry :)

**Comment by fkorotkov** [comment]
Good idea! Updated description on Docker Hub.
