### ISSUE TITLE
Any recomendation for image to run flutter linux desktop?

### ISSUE THREAD

**Issue by MosheYamini** [cirruslabs/docker-images-flutter#268]
I dont want to use blown up image with libs that we have to install for building the bundle.
I need an image to run flutter linux desktop. Any recomndation?

**Comment by Lukas-Heiligenbrunner** [comment]
You could build one yourself...
eg. sth like this:
```
FROM ubuntu:rolling
USER root

ENV FLUTTER_HOME=${HOME}/sdks/flutter \
    FLUTTER_VERSION=3.7.0
ENV FLUTTER_ROOT=$FLUTTER_HOME

ENV PATH ${PATH}:${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin

RUN apt-get update
RUN apt-get install -y --no-install-recommends curl ca-certificates git unzip cmake make ninja-build clang pkg-config libgtk-3-dev libssl-dev


# install flutter
RUN git clone --depth 1 --branch ${FLUTTER_VERSION} https://github.com/flutter/flutter.git ${FLUTTER_HOME}

RUN flutter doctor \
    && chown -R root:root ${FLUTTER_HOME} \
    && flutter config --enable-linux-desktop \
    && flutter precache --linux

RUN apt-get remove -y curl unzip
RUN apt-get autoremove -y
RUN apt-get clean
```

**Comment by MosheYamini** [comment]
Thanks @Lukas-Heiligenbrunner . But do i have to install flutter to run linux desktop? I am seeking for slim image without extra installs.

**Comment by Lukas-Heiligenbrunner** [comment]
Oh, you don't want the container to build your linux app, you want to run the gui app inside the container? 
Basically you don't need flutter installed to run the app you only need the libgtk libs.

**Comment by bartekpacia** [comment]
Yeah, you don't need Flutter installed for running a Flutter app. I think this request if out of scope. cc @fkorotkov
