### ISSUE TITLE
How to use this in gitlab CI/CD

### ISSUE THREAD

**Issue by dditim** [cirruslabs/docker-images-flutter#274]
Hi,

we were working with "cirrusci/flutter:latest" in our gitlab Pipeline.
However it seems we reached a point where we have to update to a newer flutter version.

When checking the docker image in our gitlab-ci.yaml I realised that it was deprecated some months ago. The docker image states 
![image](https://github.com/cirruslabs/docker-images-flutter/assets/135109604/e97f6010-f1e4-4653-9e6e-adf4c169341c)

referencing to this git repository while this git repository states:
![image](https://github.com/cirruslabs/docker-images-flutter/assets/135109604/792ece1d-1799-4801-b484-4a43d82ab44b)

where the Link behind "use it in CI" links to the deprecated docker image.

So, how to use this new repo in a gitlab pipeline or am I missing something?

Thank you!

**Comment by slaci** [comment]
They migrated it to Github packages. The new image is visible on your screenshot: `ghcr.io/cirruslabs/flutter`.

You can find the available tags here (on the `Code` tab at the right there is a `Packages` part where you can click `flutter` to get there): https://github.com/cirruslabs/docker-images-flutter/pkgs/container/flutter

So basically you replace `cirrusci/flutter` by `ghcr.io/cirruslabs/flutter`

**Comment by dditim** [comment]
Thank you that seems to do the trick :)
