### ISSUE TITLE
Gradle 8 requires Java 17

### ISSUE THREAD

**Issue by boldt** [cirruslabs/docker-images-flutter#278]
We bumped our project to Gradle 8, e.g., `gradle-wrapper.properties ` to 

```
classpath 'com.android.tools.build:gradle:8.0.2'
```

and `build.gradle` to:

```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.1.1-all.zip
```

We're using the image `ghcr.io/cirruslabs/flutter:3.10.2` and it throws the following error:

```
  > Android Gradle plugin requires Java 17 to run. You are currently using Java 11.
      Your current JDK is located in /usr/lib/jvm/java-11-openjdk-amd64
      You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

**Comment by davidmartos96** [comment]
@fkorotkov Thanks for merging! Can the flutter image push be triggered manually or is a PR needed?
Otherwise it would still be using the previous android-sdk image with Java 11

**Comment by davidmartos96** [comment]
> There is conveniently a new beta version. So I bumped it https://github.com/cirruslabs/docker-images-flutter/commit/fae42bde7eb9d01b5868072dfa6e92b18d3e625c

Great, thank you!
