### ISSUE TITLE
Flutter 3.10.7 missing image

### ISSUE THREAD

**Issue by iassal** [cirruslabs/docker-images-flutter#284]

**Comment by fkorotkov** [comment]
It was bumped straight to `3.13.0` in #283. You can use `3.10.6` in the meantime.

**Comment by iassal** [comment]
We are using 3.10.7 as it contains a critical fix in iOS and we don't want to upgrade to 3.13 yet as it was just released? Is there any workarounds? I can do any effort if needed.

Thanks

**Comment by fkorotkov** [comment]
Manually [triggered a build](https://cirrus-ci.com/build/5460443473379328) for `3.10.7` and [it's available now](https://github.com/cirruslabs/docker-images-flutter/pkgs/container/flutter/120133386?tag=3.10.7).

**Comment by iassal** [comment]
@fkorotkov Thanks a lot!
