### ISSUE TITLE
error

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [cirruslabs/docker-images-flutter#30]
![image](https://user-images.githubusercontent.com/29608698/64834529-a32f5e00-d5b8-11e9-9c2d-3453256b96fc.png)

macos 10.14.6

**Comment by fkorotkov** [comment]
@diego-lipinski-de-castro can you reproduce it locally with the latest version of flutter? The image was updated 2 days ago with the latest stable version of Flutter. 

I can see there is some warning in the console. And the error says it tried to read files from `/Users/lipinski` which is not available in the container.

**Comment by betorcs** [comment]
I had the same issue, this solves to me:

```bash
docker run --rm -it -v `pwd`:/build --workdir /build cirrusci/flutter:stable bash -c "rm -rf .packages && flutter test"
```

**Comment by fkorotkov** [comment]
Seems that might be related to the Linux container not able to use macOS's `.packages` folder. 🤔 @betorcs thank you for the workaround!
