### ISSUE TITLE
Flutter 3.16.8 missing image

### ISSUE THREAD

**Issue by dbebawy** [cirruslabs/docker-images-flutter#307]
Cause: The "Check Flutter versions" action is continuously failing.

![screencapture-github-cirruslabs-docker-images-flutter-pkgs-container-flutter-2024-01-23-11_59_00](https://github.com/cirruslabs/docker-images-flutter/assets/3606603/389c6eea-b363-4440-806c-f2268d5edda4)

![screencapture-github-cirruslabs-docker-images-flutter-actions-2024-01-23-11_59_14](https://github.com/cirruslabs/docker-images-flutter/assets/3606603/20ad23d7-999e-43f9-9da0-8dec83e18224)

**Comment by fkorotkov** [comment]
It broke because we moved our org to GitHub Enterprise Cloud. Fixed now.
