### ISSUE TITLE
Issues with built releases

### ISSUE THREAD

**Issue by FluffyDiscord** [cirruslabs/docker-images-flutter#309]
I am using this image to build release version of my app in Gitlab CI. Using the same command on my local machine vs this docker image produces different apps.

Differences:
- **size** - for some reason they differ by 500KB, the CI is larger
- **conflicting package** - updating currently installed app is not possible as I get "App not installed as package conflicts with an existing package.", local builds work just fine

I have checked both locally built and CI built apps using [apkanalyzer](https://developer.android.com/tools/apkanalyzer) and they both produce the same package name (bundle id), same build version and name, yet the CI is somehow different.

I have no idea what would be the cause of this. I am using the same flutter version in docker image and on my local machine, so that should not be the difference.

**Comment by bartekpacia** [comment]
Could you provide a repo that would server as a reproducible sample?
