### ISSUE TITLE
git or ssh is not installed in cirrusci/flutter:latest

### ISSUE THREAD

**Issue by masashi-sutou** [cirruslabs/docker-images-flutter#33]
I use this image on CircleCI. I got this error.

> Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
 
I think the reason for this error is that it is no longer push `cirrusci/flutter:base` after [this commit](https://github.com/cirruslabs/docker-images-flutter/commit/bfa2456b2d0e1387c2b57e90995094c85fa8711e#diff-d3a8e10c4500c56b6b3cd810dd529558L1), and is not installed git or ssh [cirrusci/android-sdk:29](https://hub.docker.com/layers/cirrusci/android-sdk/29/images/sha256-c00ae900172f73c6c89ac3f052a77f505286f1db4518ffcc3937323636c39550). `flutter:base` installed git and openssh-client by apt-get [command](https://hub.docker.com/layers/cirrusci/flutter/base/images/sha256-b3c111cf1feae67c432c21d719d11f2fd102399820c9e443f08a5f02c28c7f35).

I think `cirrusci/flutter:base` is installed latest android SDK 29. it does not need to use `FROM cirrusci/android-sdk:29`.

Why did you change it to use `FROM cirrusci/android-sdk:29` in [this commit](https://github.com/cirruslabs/docker-images-flutter/commit/bfa2456b2d0e1387c2b57e90995094c85fa8711e#diff-d3a8e10c4500c56b6b3cd810dd529558L1) ?

**Comment by fkorotkov** [comment]
Addressing in the base to minimize amount of layers: https://github.com/cirruslabs/docker-images-android/pull/19
