### ISSUE TITLE
Gitlab job failing

### ISSUE THREAD

**Issue by abduzar** [cirruslabs/docker-images-flutter#43]
Here is part of the log :
3340 [  +16 ms] Running "flutter pub get" in quest-runner-x... (completed in 8.3s)
3341 [  +91 ms] Found plugin flutter_keyboard_visibility at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
3342 [  +16 ms] Found plugin flutter_webview_plugin at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/
3343 [   +4 ms] Found plugin google_maps_flutter at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+15/
3344 [ +130 ms] Found plugin flutter_keyboard_visibility at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
3345 [   +7 ms] Found plugin flutter_webview_plugin at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.10+1/
3346 [   +2 ms] Found plugin google_maps_flutter at /home/cirrus/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.21+15/
3347 [  +65 ms] "flutter apk" took 8,652ms.
3348 [!] The build process for Android has changed, and the current project configuration is no longer valid. Please consult
3349 https://github.com/flutter/flutter/wiki/Upgrading-Flutter-projects-to-build-with-gradle
3350 for details on how to upgrade the project.
3351 #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
3352 #1      _exitWithProjectNotUsingGradleMessage (package:flutter_tools/src/android/gradle.dart:669:3)
3353 #2      buildGradleApp (package:flutter_tools/src/android/gradle.dart:231:5)
3354 #3      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
3355 #4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
3356 #5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
3357 <asynchronous suspension>
3358 #6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
3359 <asynchronous suspension>
3360 #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
3361 #8      _rootRun (dart:async/zone.dart:1126:13)
3362 #9      _CustomZone.run (dart:async/zone.dart:1023:19)
3363 #10     _runZoned (dart:async/zone.dart:1518:10)
3364 #11     runZoned (dart:async/zone.dart:1465:12)
3365 #12     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
3366 #13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
3367 #14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
3368 #15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
3369 <asynchronous suspension>
3370 #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
3371 #17     _rootRun (dart:async/zone.dart:1126:13)
3372 #18     _CustomZone.run (dart:async/zone.dart:1023:19)
3373 #19     _runZoned (dart:async/zone.dart:1518:10)
3374 #20     runZoned (dart:async/zone.dart:1465:12)
3375 #21     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
3376 #22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
3377 #23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
3378 #24     new Future.sync (dart:async/future.dart:224:31)
3379 #25     CommandRunner.run (package:args/command_runner.dart:112:14)
3380 #26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
3381 #27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
3382 #28     _rootRun (dart:async/zone.dart:1126:13)
3383 #29     _CustomZone.run (dart:async/zone.dart:1023:19)
3384 #30     _runZoned (dart:async/zone.dart:1518:10)
3385 #31     runZoned (dart:async/zone.dart:1502:12)
3386 #32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
3387 <asynchronous suspension>
3388 #33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
3389 #34     _rootRun (dart:async/zone.dart:1126:13)
3390 #35     _CustomZone.run (dart:async/zone.dart:1023:19)
3391 #36     _runZoned (dart:async/zone.dart:1518:10)
3392 #37     runZoned (dart:async/zone.dart:1465:12)
3393 #38     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
3394 #39     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
3395 #40     run (package:flutter_tools/runner.dart:50:10)
3396 #41     main (package:flutter_tools/executable.dart:65:9)
3397 #42     main (file:///home/cirrus/sdks/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
3398 #43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
3399 #44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
3400 ERROR: Job failed: exit code 1

Please advice , updrade to android x was done . Local build goes fine

**Comment by fkorotkov** [comment]
@abduzar did you figure it out?
