### ISSUE TITLE
cirrusci/flutter:stable "pub deps" fails

### ISSUE THREAD

**Issue by k-paxian** [cirruslabs/docker-images-flutter#44]
Using `cirrusci/flutter:stable`

When running `pub deps` fails 🔴  with
`Cannot open file, path = 'version' (OS Error: No such file or directory, errno = 2)`

When running `flutter pub deps` ✔️

**Comment by fkorotkov** [comment]
Try to `sudo`. I believe your executor doesn't respect `USER` directive.

**Comment by fkorotkov** [comment]
Closing in favor of #45. This issue is coming too frequently. Instead of waiting for other to comply with `USER` let's just remove it.

**Comment by k-paxian** [comment]
Seriously? What's the difference between pub deps and flutter pub deps? Flutter is using sudo under the hood? Don't think so.

**Comment by k-paxian** [comment]
Btw, I was using Root user.

**Comment by fkorotkov** [comment]
`No such file or directory` looks like permissions issue which most likely is caused by a non-root user (`cirrus`) trying access a directory owned by root (by default Docker mounts folders without respecting `USER` see https://github.com/moby/moby/issues/2259).

**Comment by fkorotkov** [comment]
If you are using root, could you please provide steps to reproduce?

**Comment by k-paxian** [comment]
https://github.com/sakebook/actions-flutter-pub-publisher/blob/master/Dockerfile
With this contents.

**Comment by k-paxian** [comment]
And using GitHub actions runner.
https://github.com/k-paxian/dart-package-publisher/commit/4ab281f63c18d741cb613748fec68f73e6459a15/checks?check_suite_id=416141551

<<Dart package>> step has this error.
