### ISSUE TITLE
Get rid of cirrus user

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/docker-images-flutter#45]
Use root by default to avoid permission error from things like GitLab.

**Comment by neokree** [comment]
If you are using GitLab, you can get rid of errors using the command:
`sudo chown -R cirrus:cirrus .`

As a first command in the CI. 
This will ensure that the code have the right permission to be executed for every tool (like `build_runner`)

**Comment by burtsevyg** [comment]
Use gitlab with dind and get:


`sudo: setrlimit(RLIMIT_CORE): Operation not permitted`
with stable version of image

try to fix:

```
RUN sudo chown -R cirrus:cirrus /etc/sudo.conf
RUN sudo echo "Set disable_coredump false" >> /etc/sudo.conf
```
get:
```
sudo: setrlimit(RLIMIT_CORE): Operation not permitted
chown: cannot access '/etc/sudo.conf': No such file or directory
```
I suppose I'm trapped in an infinite loop.

**Comment by fkorotkov** [comment]
@burtsevyg try to chown only folder with your project.

**Comment by burtsevyg** [comment]
@fkorotkov now it works with dind, but on simple docker host it doesn't need. 
Also there are many:
`sudo: setrlimit(RLIMIT_CORE): Operation not permitted`
in the log. It is relevant to your issue.

**Comment by aleksandr-m** [comment]
@fkorotkov Any time estimate for this?

**Comment by burtsevyg** [comment]
> This is a `sudo` inside a container issue: [sudo-project/sudo#42](https://github.com/sudo-project/sudo/issues/42)
> 
> Should be fixed eventually with a new release of `sudo`.

Or new version of ubuntu in 2022.
