### ISSUE TITLE
Publish additional set of docker images with hard coded Flutter version

### ISSUE THREAD

**Issue by ened** [cirruslabs/docker-images-flutter#47]
Given that I use a docker image with this configuration:

```
FROM cirrusci/flutter:stable

RUN sdkmanager ndk-bundle
RUN sdkmanager 'cmake;3.10.2.4988404'
```

Then todays Flutter version may be different from tomorrow, thus making the job of our QA department tedious due to the fact that Flutter version upgrades always require a full test cycle.

It would be beneficial if we can instead depend on a specific version via the Dockerfile (this will increase build speed a bit as well), like so:

```
FROM cirrusci/flutter:1.13.6

RUN sdkmanager ndk-bundle
RUN sdkmanager 'cmake;3.10.2.4988404'
```

**Comment by fkorotkov** [comment]
It’s already there. 🙌 Check available tags her: https://hub.docker.com/r/cirrusci/flutter/tags
