### ISSUE TITLE
flutter build web--Target dart2js failed

### ISSUE THREAD

**Issue by laohubzy** [cirruslabs/docker-images-flutter#48]
Dear flutter community

I’m encountering trouble while deploying flutter web project in linux on docker. 

**Problem**
I run `flutter build web` on Linux and I get an error that
 `Target dart2js failed: Exception: 
Exception: Failed to compile application for the Web.` .

I find when `import 'package:flutter/material.dart';` in my code, it will build failed.
But if I remove `import 'package:flutter/material.dart'`, it work successfully .
Even if I add code` import 'package:flutter/painting.dart';`, it also can build successfully;

`
import 'package:flutter/material.dart';
void main() {}
`

**My Dockerfile content.**

FROM cirrusci/flutter:beta-web
USER root
WORKDIR /app 
COPY . /app
RUN ls \
&& which flutter \
&& flutter config --enable-web  \
&& flutter --version \
&& flutter pub get  \
&& flutter build web

**logs:**
**Target dart2js failed: Exception: 
Exception: Failed to compile application for the Web.**

`
[flutter_web_demo] $ /bin/sh -xe /tmp/jenkins2234820334501684151.sh
+ sh ./setup.sh
Sending build context to Docker daemon  351.7kB

Step 1/5 : FROM cirrusci/flutter:beta-web
 ---> df26f0edcdf7
Step 2/5 : USER root
 ---> Running in c3852c680c28
Removing intermediate container c3852c680c28
 ---> ff82dc765541
Step 3/5 : WORKDIR /app
 ---> Running in 915b1c1545fa
Removing intermediate container 915b1c1545fa
 ---> 5e624a0a7476
Step 4/5 : COPY . /app
 ---> 6c3c03b231c9
Step 5/5 : RUN ls && which flutter && flutter config --enable-web  && flutter --version && flutter pub get  && flutter build web
 ---> Running in f817c6c3fc49
android
conf.nginx
Dockerfile
ios
lib
pubspec.yaml
README.md
setup.sh
web
/home/cirrus/sdks/flutter/bin/flutter
Setting "enable-web" value to "true".

You may need to restart any open editors for them to read new settings.
Flutter 1.13.6 • channel unknown • unknown source
Framework • revision 659dc8129d (6 weeks ago) • 2019-12-30 09:24:47 -0800
Engine • revision bdc9708d23
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
Running "flutter pub get" in app...                                62.9s
Downloading Web SDK...                                             18.6s
Compiling lib/main.dart for the Web...                          [91mTarget dart2js failed: Exception: 
Exception: Failed to compile application for the Web.
[0m
Compiling lib/main.dart for the Web...                             29.6s
`
**environment**
 
CentOS 7.5 64

`
Flutter 1.13.6 • channel unknown • unknown source
Framework • revision 659dc8129d (6 weeks ago) • 2019-12-30 09:24:47 -0800
Engine • revision bdc9708d23
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
`
 flutter config
`
Settings:
  enable-web: true 
`

**Comment by fkorotkov** [comment]
Hey @laohubzy,

I think the best course of action will be to create a small project that reproduces the issue and/or check with the community though [official community channels](https://flutter.dev/community) (maybe [StackOverflow](https://stackoverflow.com/tags/flutter)?).

**Comment by laohubzy** [comment]
I tried another image and had the same problem, so I changed my mind and build it before uploading. Thank you！
