### ISSUE TITLE
Unit test running for flutter web fail beacause it can't find google-chrome

### ISSUE THREAD

**Issue by hunght** [cirruslabs/docker-images-flutter#53]
I try to run unit-test with cirrusci/flutter:v1.15.17-web  , it return error on my gitlab ci/cd:
` Running "flutter pub get" in _flutter_web_build_script...           3.3s
 00:00 +0 -1: loading /builds/herocrazy/flutter_web/test/widget_test.dart [E]                                                                                                                           
   Failed to load "/builds/herocrazy/flutter_web/test/widget_test.dart": Invalid argument(s): Cannot find executable for google-chrome.`

**Comment by fkorotkov** [comment]
@hunght since it's Linux you'll need to use `chromium-browser` instead of `google-chrome`.
