### ISSUE TITLE
Error: No pubspec.yaml file found in the current working directory. 

### ISSUE THREAD

**Issue by xiaoqianghaochi** [cirruslabs/docker-images-flutter#54]
1、docker run --rm -it -v $PWD:/build --workdir /build cirrusci/flutter:stable flutter test
 Error: No pubspec.yaml file found in the current working directory.
Run this command from the root of your project. Test files must be called
*_test.dart and must reside in the package's 'test' directory (or one of its
subdirectories).
![image](https://user-images.githubusercontent.com/12827386/79442195-cb79b200-800a-11ea-9977-e39bb4e86541.png)

**Comment by fkorotkov** [comment]
I believe it's the same issue as #45
