### ISSUE TITLE
Adding yq YAML processor for processing yaml files

### ISSUE THREAD

**Issue by mark-veenstra** [cirruslabs/docker-images-flutter#62]
Hi,

It could be handy to have `yq` installed in the image for YAML file processing. For example to get the version from a pubspec.yaml during ci/cd builds.

See: https://github.com/mikefarah/yq#on-ubuntu-1604-or-higher-from-debian-package

Regards,

Mark

**Comment by vladaman** [comment]
Is there any example how can we extract app version from pubspec.yaml ? Thanks!

**Comment by bartekpacia** [comment]
@vladaman and future readers: you can try this:

```
$ yq '.version' pubspec.yaml
1.0.0+1
```

**Comment by bartekpacia** [comment]
cc @fkorotkov This was resolved by https://github.com/cirruslabs/docker-images-android/pull/63
