### ISSUE TITLE
Update dart sdk?

### ISSUE THREAD

**Issue by novas1r1** [cirruslabs/docker-images-flutter#63]
Hey there,
I'm using the "flutter:stable" in my gitlab-ci. Yesterday was the day when all the ci pipelines broke down due to a version conflict with a package I guess.
I'm using flutter 1.17.1 and dart 2.8.2 locally - both stable versions - and it works perfectly locally. I'm not really experienced with docker, but I guess the dart sdk should be updated from 2.7.x to 2.8.x?

Best regards
Verena

**Comment by fkorotkov** [comment]
Hey @novas1r1, I think your pull of `cirrusci/flutter:stable` might be out of date. It should have Flutter `v1.17.1` and Dart `2.8.2` as you have locally:

```
~ $ docker run cirrusci/flutter:stable flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.17.1, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
~ $ docker run cirrusci/flutter:stable dart --version
Dart VM version: 2.8.2 (stable) (Mon May 11 15:06:42 2020 +0200) on "linux_x64"
```

**Comment by novas1r1** [comment]
Hi @fkorotkov, 
I "fixed" it by using specific flutter version "cirrusci/flutter:1.17.1". Using the stable is still an issue. Started some days ago when it was updated. I'm fine with the above solution so for me theres no need to dig deeper. Thank you :)!
