### ISSUE TITLE
Locale Error in Flutter Docker Container

### ISSUE THREAD

**Issue by SebSeifert** [cirruslabs/docker-images-flutter#8]
In the Docker Image cirrusci/flutter:latest the Console is always spammed with:
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
On Ubuntu 18.04 with Gitlab Runner.

**Comment by fkorotkov** [comment]
@SebSeifert which command are you executing in the container?

**Comment by SebSeifert** [comment]
Here is my gitlab-ci.yml

image: cirrusci/flutter:latest

variables:
before_script:
  - flutter channel beta
  - flutter upgrade
  
stages:
  - test

unitTests:
  stage: test
  script:
    - flutter test lib/main.dart
