### ISSUE TITLE
Why not Dockerfile upgrade to android sdk 30?

### ISSUE THREAD

**Issue by cuong-le** [cirruslabs/docker-images-flutter#81]
Currently I see the Dockerfile is "FROM cirrusci/android-sdk:29".

Why not upgrade to "FROM cirrusci/android-sdk:30" ?

**Comment by fkorotkov** [comment]
Isn't it in preview still? I see it's rc4 for 30 here: https://developer.android.com/studio/releases/build-tools

**Comment by fkorotkov** [comment]
Fixed in #93
