### ISSUE TITLE
Connect to the emulator

### ISSUE THREAD

**Issue by JAGDISH0008** [cirruslabs/docker-images-flutter#90]
How can we connect the emulator device to the docker-container

**Comment by fkorotkov** [comment]
How do you usually do it? I don't have practical experience but since you can access a port on your host machine from within the container, seems you'll be able to connect for the test device.

**Comment by fkorotkov** [comment]
Closing the issue since haven't got any additional information. Seems on macOS it should be working as is and on Linux with `--network=host` container will be able to connect to a device on port on the host machine.
