### ISSUE TITLE
Since a few minutes the cirrus user and group is gone (v1.20.3)

### ISSUE THREAD

**Issue by loeffel-io** [cirruslabs/docker-images-flutter#94]
latest: Pulling from cirrusci/flutter
--
2 | Digest: sha256:c0806697809045748f6fdf86a9d7891637dbeb51c97136261be1353b3bcab6cd
3 | Status: Image is up to date for cirrusci/flutter:latest
4 | + sudo chown -R cirrus:cirrus .
5 | chown: invalid user: ‘cirrus:cirrus’

**Comment by fkorotkov** [comment]
Yes, it was caused by #93 which fixed the long standing inconveniences in #45. There was no easy way to do this breaking changes so it was paired with the Android upgrade.

**Comment by fkorotkov** [comment]
You don't need to `chown` anymore.

**Comment by loeffel-io** [comment]
sweet, thanks for the info!

**Comment by fkorotkov** [comment]
@loeffel-io please let me know if you'll have any issues with all breaking changes. And sorry for the inconviniences!

**Comment by loeffel-io** [comment]
Everything works fine, thanks!
