### ISSUE TITLE
FilteringTextInputFormatter.digitsOnly is undefined

### ISSUE THREAD

**Issue by peterwvj** [cirruslabs/docker-images-flutter#98]
I use `cirrusci/flutter:latest` to build a Flutter application, which works well. However, I noticed that that using `FilteringTextInputFormatter.digitsOnly` is giving me errors although `FilteringTextInputFormatter` seems to have replaced `WhitelistingTextInputFormatter`, which presumably is deprecated. In particular, my pipeline produces the following error, which I was able to produce on 19-Sep-2020 22:26:48 (Danish time):

```
Analyzing fit_app_master...                                     

  error • Undefined name 'FilteringTextInputFormatter'
```

My workaround is to switch to `WhitelistingTextInputFormatter.digitsOnly` although this is not ideal. When using `FilteringTextInputFormatter.digitsOnly`, I can build my flutter application locally without problems. Here's my local workstation setup:

```
λ flutter --version
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (6 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```
So my question is: is there something in the docker image that needs to be updated?

I should say that I'm fairly new to Flutter/Dart so it could be that I'm missing something.

Thanks in advance.

**Comment by fkorotkov** [comment]
@peterwvj do you have `package:flutter/services.dart` imported in your file with the error?

**Comment by peterwvj** [comment]
Hi @fkorotkov , thanks for you quick response. Yes, I have.

**Comment by peterwvj** [comment]
This seems to be required in order to use `FilteringTextInputFormatter.digitsOnly`.

**Comment by fkorotkov** [comment]
Just wanted to double check since you haven't included sources. It does seem like the image contains the file and is not corrupted:

```bash
$ docker run cirrusci/flutter:latest cat /sdks/flutter/packages/flutter/lib/src/services/text_formatter.dart | grep "class FilteringTextInputFormatter"
class FilteringTextInputFormatter extends TextInputFormatter {
```

Not sure what's going on there. 🤔 And it's working for you locally, right?

**Comment by peterwvj** [comment]
Yes, I can't include the source, sorry. It builds locally without problems.

Thanks for confirming that the file is included in the image. For now I'll assume that the problem is at my end. I'll check my Jenkins setup and get back to you shortly.

**Comment by peterwvj** [comment]
So I managed to get it to work. I wrongly assumed that my Jenkins server would always pull the latest image, which it didn't. Sorry for that. Changing the `Jenkinsfile` to always pull the latest image fixed the problem:

```
pipeline {
    agent {
        docker {
            image 'cirrusci/flutter:latest'
            alwaysPull true
        }
    }
   ....
```
Again, thanks for helping me track down the problem :)

**Comment by fkorotkov** [comment]
@peterwvj shameless plug 😅 You can try using [Cirrus CLI](https://github.com/cirruslabs/cirrus-cli) - it always pulls the images and also you can easily run it locally to reproduce issues.

**Comment by peterwvj** [comment]
Haha :) Cirrus CLI actually looks pretty cool. Might look into that at some point.
